#! /bin/bash

#####################################
# Written by: crimsonmane           #
# github.com/crimsonmane/nightshade #
#         revised 20131224          #
#####################################

initialSetup(){
  medibuntu
  tput setaf 1 #Red text
  echo "Checking if -pastebinit- is installed... Updating -inxi- in order to provide consistent output... Enter password to continue or CTRL+C to skip (-inxi- updates often and so should you)..."
  tput sgr0 #Reset text
  if ! dpkg -l | grep pastebinit
  then
    sudo aptitude install pastebinit
  fi
  sudo inxi -U
}

updateFerret(){
  xdg-open https://github.com/crimsonmane/nightshade/wiki/ferret-wiki#get-ferret
}

shareLink(){
  echo "^^ Share this URL with your helper!^^"
}

sniffSound(){
  inxi -Sc0 > temp.file
  inxi -Axc0 >> temp.file
  case $mintVersion in
    *"Mint 16"*)
      find ~/.config/pulse -name \*source\* -printf '\n\n%c\n%f\n' -execdir cat {} ';' >> temp.file
      break;;
    *)
      find ~/.pulse -name \*source\* -printf '\n\n%c\n%f\n' -execdir cat {} ';' >> temp.file
      break;;
  esac
  pastebinit temp.file
  shareLink
  rm temp.file
}

XorgLog(){
  egrep -wi 'WW|EE' /var/log/Xorg.0.log | pastebinit
  shareLink
}

syslog(){
  { inxi -c0 -FSRzdfulportcm20; egrep -i 'warn|error|critical' /var/log/syslog; } | pastebinit
  shareLink
}

medibuntu(){
  if inxi -r | grep -i medibuntu
  then
    echo
    echo "Medibuntu found in sources, causing update issues. Confirm removal by entering password (because sudo is needed), or CTRL+C to skip."
    echo
    if [ -a /etc/apt/sources.list.d/medibuntu* ]
    then
      sudo rm /etc/apt/sources.list.d/medibuntu*
    fi
      sudo cp /etc/apt/sources.list /etc/apt/sources.list.bkup
      sudo sed -i '/medibuntu/d' /etc/apt/sources.list
      echo
      echo "Medibuntu has been removed from sources. Confirm by running Update Manager."
      echo
    else
    echo "Medibuntu not found on this system. That's good!"
  fi
}

ps3ms(){
  clear
  echo "$title1 - PS3 Media Server"
  echo "$title2"
  select toDo in "Install" "Remove" "Do Nothing"
  do
    case $toDo in
      "Install")
	sudo apt-add-repository ppa:happy-neko/ps3mediaserver
	sudo aptitude update
	sudo aptitude install ps3mediaserver
	break;;
      "Remove")
	sudo aptitude purge -y ps3mediaserver
	sudo apt-add-repository --remove ppa:happy-neko/ps3mediaserver
	break;;
      *)
	break;;
    esac
  done
}

plex(){
  clear
  echo "$title1 - Plex Media Server"
  echo "$title2"
  select toDo in "Install" "Remove" "Do Nothing"
  do
    case $toDo in
      "Install")
	firefox http://www.plexapp.com/getplex/
	break;;
      "Remove")
	sudo aptitude purge -y plexmediaserver
	break;;
      *)
	break;;
    esac
  done
}

netflixDesktop(){
  clear
  echo "$title1 - netflix-desktop"
  echo "$title2"
  select toDo in "Install" "Remove" "Do Nothing"
  do
    case $toDo in
      "Install")
	if ! dpkg -l | grep pipelight-multi
	then
	  sudo apt-add-repository ppa:ehoover/compholio
	fi
	sudo aptitude update
	sudo aptitude install -y netflix-desktop
	break;;
      "Remove")
	sudo aptitude purge -y netflix-desktop
	if ! dpkg -l | grep pipelight-multi
	then
	  sudo apt-add-repository --remove ppa:ehoover/compholio
	fi
	break;;
      *)
	break;;
    esac
  done
}

pipelight(){
  clear
  echo "$title1 - Netflix/Pipelight"
  echo "$title2"
  select toDo in "Install" "Remove" "Do Nothing"
  do
    case $toDo in
      "Install")
	if ! dpkg -l | grep pipelight
	then
	  sudo aptitude purge pipelight
	fi
	if ! dpkg -l | grep netflix-desktop
	then
	  sudo apt-add-repository ppa:ehoover/compholio
	fi
	sudo apt-add-repository ppa:mqchael/pipelight
	sudo aptitude update
	sudo aptitude install pipelight-multi
	sudo pipelight-plugin --enable silverlight
	rm -rf ~/.wine-pipelight
	echo "*****************************************************************"
	echo "* Please install both firefox addons that are about to pop up.  *"
	echo "* Sometimes UAC doesn't work and you need to use the Overrider. *"
	echo "* It's up to you to play with these to get netflix.com to work. *"
	echo "* If your browser is open, please close it now.                 *"
	echo "* If firefox is not your desired browser, it's up to you to     *"
	echo "*                                get these addons yourself.     *"
	echo "*****************************************************************"
	read -n1 -r -p "Press any key to continue..."
	firefox https://addons.mozilla.org/en-US/firefox/addon/user-agent-overrider/ https://addons.mozilla.org/en-us/firefox/addon/uacontrol/
	break;;
      "Remove")
	sudo aptitude purge -y pipelight-multi
	sudo apt-add-repository --remove ppa:mqchael/pipelight
	if ! dpkg -l | grep netflix-desktop
	then
	  sudo apt-add-repository --remove ppa:ehoover/compholio
	fi
	break;;
      *)
	break;;
    esac
  done
}

handbrake(){
  clear   echo "$title1 - Handbrake"
  echo "$title2"
  select toDo in "Install" "Remove" "Do Nothing"
  do
    case $toDo in
      "Install")
	sudo add-apt-repository ppa:stebbins/handbrake-releases
	sudo aptitude update
	sudo aptitude install -y handbrake-gtk handbrake-cli
	break;;
      "Remove")
	sudo aptitude purge -y handbrake-gtk handbrake-cli
	sudo apt-add-repository --remove ppa:stebbins/handbrake-releases
	break;;
      *)
	break;;
    esac
  done
}

chrome(){
  clear
  echo "$title1 - Google Chrome"
  echo "$title2"
  select toDo in "Install" "Remove" "Do Nothing"
  do
    case $toDo in
      "Install")
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/ferret-chrome.list'
	sudo aptitude update
	sudo aptitude install -y google-chrome-stable
	break;;
      "Remove")
	sudo aptitude purge -y google-chrome-stable
	sudo rm /etc/apt/sources.list.d/ferret-chrome.list
	break;;
      *)
	break;;
    esac
  done
}

bootRepair(){
  clear
  echo "$title1 - Boot Repair"
  echo "$title2"
  select toDo in "Install & Launch" "Remove" "Do Nothing"
  do
    case $toDo in
      "Install & Launch")
	if ! dpkg -l | grep boot-repair
	then
	  sudo apt-add-repository ppa:yannubuntu/boot-repair
	  sudo aptitude update
	  sudo aptitude install -y boot-repair
	fi
	boot-repair &
	break;;
      "Remove")
	sudo aptitude purge -y boot-repair
	sudo apt-add-repository --remove ppa:yannubuntu/boot-repair
	break;;
      *)
	break;;
    esac
  done
}

video(){
  echo "Section not yet written."
}

audio(){
  clear
  echo "$title1 - Troubleshoot Audio"
  echo "$title2"
  select toDo in "Do Nothing" "The only audio device shown is Dummy Output"
  do
    case $toDo in
      "The only audio device shown is Dummy Output")
	sudo aptitude purge --safe-resolver alsa-base pulseaudio
	sudo aptitude install -y alsa-base pulseaudio
	sudo alsa force-reload
	echo "Changes will take effect when you reboot. Please reboot."
	break;;
      "Same as #2 but that fix didn't work.")
	echo "Section not written."
	break;;
      *)
	break;;
    esac
  done
}

wifi(){
  case $(inxi -Nxx) in
    *"BCM43"*)
      sudo aptitude install firmware-b43-installer b43-fwcutter
      break;;
    *)
      echo "No issues detected."
      break;;
  esac
}

propDrivers(){
  case $mintVersion in
    *"KDE"*"Mint 13"*) jockey-kde; break;;
    *"KDE"*"Mint 14"*) software-properties-kde; break;;
    *"KDE"*"Mint 15"*) software-properties-kde; break;;
    *"Mint 13"*) jockey-gtk; break;;
    *"Mint 14"*) software-properties-gtk; break;;
    *"Mint 15"*) software-properties-gtk; break;;
    *"Mint 16"*) driver-manager; break;;
  esac
}

popularSoftware(){
  clear
  echo "$title1 - Software Menu"
  echo "$title2"
  select toDo in "Do Nothing" "Plex Media Server" "PS3 Media Server" "Netflix-Desktop" "Netflix/Pipelight" "Google Chrome" "Handbrake"
  do
    case $toDo in
      "Do Nothing") toDo=-1; break;;
      "Plex Media Server") plex; break;;
      "PS3 Media Server") ps3ms; break;;
      "Netflix-Desktop") netflixDesktop; break;;
      "Netflix/Pipelight") pipelight; break;;
      "Google Chrome") chrome; break;;
      "Handbrake") handbrake; break;;
    esac
  done
}

main(){
#  toDo=0
#  while [ $toDo -ne -1 ]
#  do
    clear
    echo "Note: Menu item to remove Medibuntu repo from sources has been deleted, as this condition is identified and resolved automatically when Ferret loads."
    echo
    echo "$title1 - Main Menu"
    echo "$title2"
    select toDo in "Do Nothing" "Update Ferret" "Popular Software" "Troubleshoot Audio" "Troubleshoot Video" "Troubleshoot WiFi" "sniff sound" "sniff Xorg log" "sniff syslog" "Open Drivers Dialogue" "Boot Repair"
    do
      case $toDo in
	"Do Nothing") toDo=-1; break;;
	"Update Ferret") updateFerret; break;;
	"Popular Software") popularSoftware; break;;
	"Troubleshoot Audio") audio; break;;
	"Troubleshoot Video") video; break;;
	"Troubleshoot WiFi") wifi; break;;
	"sniff sound") sniffSound; break;;
	"sniff Xorg log") XorgLog; break;;
	"sniff syslog") syslog; break;;
	"Open Drivers Dialogue") propDrivers; break;;
	"Boot Repair") bootRepair; break;;
      esac
    done
#  done
  echo
  echo "Please 'like' my company page: https://facebook.com/nightshadePC"
  echo
  echo "Report bugs, errors, unexpected behavior, and requests:"
  echo "https://github.com/crimsonmane/nightshade/issues"
  echo
  echo "Thank you for using $title1!"
}

initialSetup
title1="Ferret (version 4)"
title2="------------------"
mintVersion=$(inxi -S)
main
